version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=teste
      - AWS_SECRET_ACCESS_KEY=teste
      - HOSTNAME=localhost
      - HOSTNAME_EXTERNAL=localhost
      - HOSTNAME_FROM_LAMBDA=localhost
      - LAMBDA_EXECUTOR=docker-reuse
      - EDGE_PORT=4566
      - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - '4566-4587:4566-4587'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
