# "service" is the name of this project. This will also be added to your AWS resource names.
service: trabalho-final

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  memorySize: 128
  region: 'us-east-1'
  environment:
    SQS_PREPARACAO_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/em-preparacao-pizzaria
    SQS_PRONTO_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/pronto-pizzaria
    DYNAMODB_TABLE: pedidos-pizzaria

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    autostart: true  # optional - Start LocalStack in Docker on Serverless deploy
    
plugins:
  - serverless-localstack

functions:
  s3Handler:
    handler: handler.s3Handler
    events:
      - s3:
          bucket: s3-pizzaria
          event: s3:ObjectCreated:*
          rules:
            - prefix: em-preparacao
      - s3:
          bucket: s3-pizzaria
          event: s3:ObjectCreated:*
          rules:
            - prefix: pronto

  sqsPreparacaoHandler:
    handler: handler.sqsHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:em-preparacao-pizzaria
          batchSize: 1
          enabled: true

  sqsProntoHandler:
    handler: handler.sqsHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:pronto-pizzaria
          batchSize: 1
          enabled: true
  
