service: trabalho-final

provider:
  name: aws
  runtime: python3.9
  memorySize: 128
  region: 'us-east-1'
  environment:
    SQS_PREPARACAO_URL: !Sub http://sqs.${self:provider.region}.aws.amazon.com/${AWS::AccountId}/em-preparacao-pizzaria
    SQS_PRONTO_URL: !Sub http://sqs.${self:provider.region}.aws.amazon.com/${AWS::AccountId}/pronto-pizzaria
    DYNAMODB_TABLE: pedidos-pizzaria

functions:
  s3Handler:
    handler: handler.s3Handler
    events:
      - s3:
          bucket: s3-pizzaria
          event: s3:ObjectCreated:*
          rules:
            - prefix: em-preparacao
      - s3:
          bucket: s3-pizzaria
          event: s3:ObjectCreated:*
          rules:
            - prefix: pronto

  sqsPreparacaoHandler:
    handler: handler.sqsPreparacaoHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:117765426352:em-preparacao-pizzaria
          batchSize: 1
          enabled: true

  sqsProntoHandler:
    handler: handler.sqsProntoHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:117765426352:pronto-pizzaria
          batchSize: 1
          enabled: true
  
